apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: main-container
        image: cuotos/helloworld
        ports:
        - containerPort: 8080
      - name: sql-proxy
        image: nginx
